### ISSUE TITLE
Feature Request: `kwctl scaffold-verification-config` command

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kwctl#170]
### Is your feature request related to a problem?

Right now, users need to craft themselves a `verication-config.yml` for [the Sigstore verification RFC](https://github.com/kubewarden/kubewarden-controller/blob/main/rfc/0003-policy-signing.md#verifying-policies).

It would be nice to provide that config for them.

### Solution you'd like

A `kwctl scaffold-verification-config` or similar, that prints to stdout a valid verification config yaml. 
The printed config can be used as the default verification config of `kwctl` if piped into the default config path, effectively opting-in users into verifying policies by Sigstore from then onwards.

The config would be one that verifies kubewarden images.

The `kwctl scaffold-verification-config` could have subcommands for different types of configs:
1. `kwctl scaffold-verification-config permissive-kubewarden`: Verifies all kubewarden images (but only prints warnings on failed verifications, kubewarden or otherwise). Eg:
   ```yaml
   ---
   apiVersion: v1
   anyOf:
     minimumMatches: 0
     signatures:
       - kind: githubAction
         owner: kubewarden
   ```
1. `kwctl scaffold-verification-config enforce-kubewarden`: Verifies all kubewarden images, error if missing signatures
   ```yaml
   ---
   apiVersion: v1
   allOf:
   - kind: githubAction
     owner: kubewarden
   ```

We could also consider prepending a short commented paragraph explaining the config usage, and also commented examples as part of the command output (so the users can edit it directly without docs) when constructing the verification config.

### Alternatives you've considered

We have thought about transparently generating the config file by default if not present; yet users would miss the context on why they get rejected policies.
