### ISSUE TITLE
Update policy metadata to handle new `contextAwareResources` attribute

### ISSUE THREAD

**Issue by flavio** [kubewarden/kwctl#427]
As described by the  [context aware policies RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0015-context-aware-policies.md), the policies that want to access Kubernetes resources at evaluation time must indicate them inside of their metadata.

The policy metadata has to be extended to store this new attribute:

```yaml
contextAwareResources:
# - apiVersion: <apiVersion>
#   kind: <kind>
- apiVersion: v1
  kind: Pod
- apiVersion: apps/v1
  kind: Deployment
- apiVersion: networking.k8s.io/v1
  Kind: Ingress
```

Currently, the policy metadata has already a `contextAware` attribute, which has a boolean value. After this change we will ignore the legacy `contextAware` attribute, both when reading the metadata and when annotating the policy.

## Admission criteria

* [x] `annotate` command must write the `contextAwareResources` attribute
* [x] `annotate` command will stop writing the `contextAware` attribute
* [x] `inspect` command will read only the `contextAwareResources` attribute. A policy that has an empty `contextAwareResources` attribute (or doesn't have it) will be considered as NOT context aware
