### ISSUE TITLE
Make kwctl aware of new severity and category annotations

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kwctl#529]
With the audit feature, we added support for new Policy Resource annotations (not to confuse with Policy metadata.yaml annotations), for policy severity and policy category. These are:
```yaml
metadata:
  annotations:
    # one of critical, high, medium, low, info. Info is used when policy is in monitor mode
    # Empty by default, set by admin
    io.kubewarden.policy.severity: "high" 
    # freefrom string. Example: "PSP", "Sample", "Signing", "Other", "Compliance"
    # Empty by default, set by admin
    io.kubewarden.policy.category: "PSP"
```

### Acceptance criteria

- Make these annotations work with `kwctl annotate` & `kwctl inspect`, so they are part of metadata.yaml as others.
- Make `kwctl scaffold` treat these, possibly setting empty values for them with an explanation comment.
