### ISSUE TITLE
Hardcoded line breaks yaml output in kwctl inspect

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kwctl#659]
### Current Behavior

Comment in [signatures output](https://github.com/kubewarden/kwctl/blob/ef8b5ac3dbacb24a91ee971af36573e1491cd7d4/src/inspect.rs#L52) breaks yaml.

```bash
~ kwctl inspect registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.7 -o yaml | yq '.'
yq: Error running jq: ScannerError: while scanning a simple key
  in "<stdin>", line 136, column 1
could not find expected ':'

~ kwctl inspect registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.7 -o yaml | grep -v 'Sigstore signatures' | yq '.'
OK
```

Invalid part:
```yaml
...
executionMode: kubewarden-wapc
policyType: kubernetes
contextAwareResources: []


Sigstore signatures

schemaVersion: 2
mediaType: application/vnd.oci.image.manifest.v1+json
config:
...
```
